# Travis CI (MIT License) configuration file for Irving Dev
# @link https://travis-ci.org/

# Bionic image has PHP versions 7.1,7.2,7.3 pre-installed
dist: bionic

# Bionic does not start mysql or memcached by default
services:
  - mysql
  - memcached

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# This "ignore" directive prevents Travis from processing branches with
# a -built suffix, thus avoiding endless loops.
if: branch =~ ^.*(?<!-built)$

# Specify when Travis should build.
branches:
  only:
    - production

cache:
  directories:
    - $HOME/.composer/cache
    - themes/irving-dev/node_modules
    - private/irving/node_modules

# Git clone depth.
git:
  depth: 1
  quiet: true

# PHP versions.
php:
  - '7.3'

matrix:
  include:
    - env: BUILD=1
    - if: type = pull_request
      env: WP_VERSION=trunk WP_THEME=irving-dev WP_PHPCS=1 PHP_LINT=1

# Prepare your build for testing.
# Failures in this section will result in build status 'errored'.
before_script:
  - |
    # Fork for build vs. test.
    if [[ $BUILD == "1" ]]; then
      echo "Installing node 10 and npm 6 ..."
      nvm install 10
      npm i -g npm@6
    else
      echo "Setting up environment for running tests ..."

      # Turn off Xdebug. See https://core.trac.wordpress.org/changeset/40138.
      phpenv config-rm xdebug.ini || echo "Xdebug not available"

      # Set up Composer.
      export PATH="$HOME/.composer/vendor/bin:$PATH"
      composer global require "phpunit/phpunit=6.1.*"

      # Set up the WordPress installation.
      export WP_CORE_DIR=/tmp/wordpress/
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      echo "define( 'JETPACK_DEV_DEBUG', true );" >> $WP_CORE_DIR/wp-tests-config.php

      # Install memcached.
      printf "\n" | pecl install --force memcached 1> /dev/null
      curl https://raw.githubusercontent.com/tollmanz/wordpress-pecl-memcached-object-cache/584392b56dc4adbe52bd2c7b86f875e23a3e5f75/object-cache.php > $WP_CORE_DIR/wp-content/object-cache.php

      # Copy the contents of this repo into the test instance of WordPress.
      rm -rf "${WP_CORE_DIR}wp-content"
      cp -R . "${WP_CORE_DIR}wp-content"

      # Set up phpcs, if necessary.
      if [[ $WP_PHPCS == "1" ]]; then
        composer global require automattic/vipwpcs
        phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs,$HOME/.composer/vendor/automattic/vipwpcs
      fi

      pwd
    fi
# Run test script commands.
# Default is specific to project language.
# All commands must exit with code 0 on success. Anything else is considered failure.
script:
  - bash bin/script-php-lint.sh theme irving-dev
  - bash bin/script-phpcs.sh theme irving-dev
  - bash bin/script-phpunit.sh theme irving-dev
  - bash bin/script-build.sh theme irving-dev

# Receive notifications for build results.
# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
  email: false
