export default {
  authors: {
    type: 'array',
    default: '',
    selector: '.post-block--authors',
    source: 'children',
  },
  ctaMessage: {
    type: 'string',
    default: '',
    selector: '.post-block--cta span',
    source: 'text',
  },
  excerpt: {
    default: '',
    selector: '.post-block--excerpt',
    source: 'html',
    type: 'string',
  },
  imageId: {
    attribute: 'data-id',
    default: 0,
    selector: '.post-block--image img',
    source: 'attribute',
    type: 'string',
  },
  imageSize: {
    attribute: 'data-size',
    default: 'thumbnail',
    selector: '.post-block--image img',
    source: 'attribute',
    type: 'string',
  },
  imageUrl: {
    attribute: 'src',
    default: '',
    selector: '.post-block--image img',
    source: 'attribute',
    type: 'string',
  },
  postType: {
    source: 'text',
    selector: '.post-block--type',
    default: '',
    type: 'string',
  },
  publishDate: {
    default: '',
    attribute: 'data-date',
    selector: '.post-block--published',
    source: 'attribute',
    type: 'string',
  },
  showAuthors: {
    default: 'true',
    attribute: 'data-visible',
    selector: '.post-block--authors',
    source: 'attribute',
    type: 'string',
  },
  showCta: {
    default: 'false',
    attribute: 'data-visible',
    selector: '.post-block--cta',
    source: 'attribute',
    type: 'string',
  },
  showPostType: {
    default: 'true',
    attribute: 'data-visible',
    selector: '.post-block--type',
    source: 'attribute',
    type: 'string',
  },
  showPublished: {
    default: 'true',
    attribute: 'data-visible',
    selector: '.post-block--published',
    source: 'attribute',
    type: 'string',
  },
  textAlignment: {
    type: 'string',
    attribute: 'data-text-align',
    default: 'left',
    selector: '.block--type--post-block',
    source: 'attribute',
  },
  title: {
    default: '',
    selector: '.post-block--title',
    source: 'text',
    type: 'string',
  },
  url: {
    attribute: 'href',
    default: '',
    selector: 'a.post-block--link',
    source: 'attribute',
    type: 'string',
  },
};
