<?php
/**
 * Sitemap module.
 *
 * @package Alleypack
 * @version 1.0.0
 * @see readme.md
 */

namespace Alleypack;

// Register the submenu page.
if ( function_exists( 'fm_register_submenu_page' ) ) {
	fm_register_submenu_page( 'sitemap-settings', 'options-general.php', __( 'Sitemap', 'alleypack' ) );
}

/**
 * Callback to activate an options page for Sitemap Settings.
 */
function fm_sitemap_settings() {
	$fm = new \Fieldmanager_Group(
		[
			'name'     => 'sitemap-settings',
			'children' => [
				'urls' => new \Fieldmanager_Link(
					[
						'label'              => __( 'Non-CMS URLs to include in the sitemap.', 'alleypack' ),
						'add_more_label'     => __( 'Add a URL', 'alleypack' ),
						'limit'              => 0,
						'one_label_per_item' => false,
					]
				),
			],
		]
	);
	$fm->activate_submenu_page();
}
add_action( 'fm_submenu_sitemap-settings', __NAMESPACE__ . '\fm_sitemap_settings' );

/**
 * Add other URLs to the sitemap generated by Jetpack.
 *
 * @param  array $urls An array of URLs.
 * @return array
 */
function jetpack_page_sitemap_other_urls( $urls ) {
	$sitemap_settings = (array) get_option( 'sitemap-settings', [] );
	return (array) ( $sitemap_settings['urls'] ?? [] );
}
add_filter( 'jetpack_page_sitemap_other_urls', __NAMESPACE__ . '\jetpack_page_sitemap_other_urls' );
